name: Build and push package

on:
  workflow_dispatch:
    inputs:
      nr_launcher_release_name:
        description: 'flowforge-nr-launcher package version'
        required: false
        default: 'nightly'
      nr_launcher_ref:
        description: 'flowforge-nr-launcher package ref'
        required: false
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - 'feat-*' 

jobs:
    # prepare:
    # runs-on: ubuntu-latest
    # outputs:
    #   release_name: ${{ steps.set_release.outputs.release_name }}
    # steps:
    #   - name: Set nigthly release
    #     id: set_release
    #     if: ${{ github.event_name == 'schedule' }}
    # run: echo "release_name=nightly" >> $GITHUB_OUTPUT
  
  package:
    permissions:
      contents: read
      packages: write
    uses: 'flowforge/github-actions-workflows/.github/workflows/publish_node_package.yml@feat-npm-publish-workflow'
    with:
      # release_name: ${{ needs.prepare.outputs.release_name}}
      package_name: flowforge-driver-localfs
      package_dependencies: |
        @flowforge/nr-launcher
        
  dispatch:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_BOT_APP_ID }}
          private_key: ${{ secrets.GH_BOT_APP_KEY }}

      - name: Trigger flowforge package rebuild
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish.yml
          repo: flowforge/flowforge
          ref: feat-publish-pipeline-poc
          token: ${{ steps.generate_token.outputs.token }}
          inputs: '{"localfs_ref": "${{ github.ref }}", "localfs_release_name": "${{ env.release_name }}"}'