name: Build and push package

on:
  workflow_dispatch:
    inputs:
      nr_launcher_release_name:
        description: 'flowforge-nr-launcher package version'
        required: false
        default: 'nightly'
      nr_launcher_ref:
        description: 'flowforge-nr-launcher package ref'
        required: false
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - 'feat-*'
      - 'main'


jobs:
  package:
    permissions:
      contents: read
      packages: write
    uses: 'flowforge/github-actions-workflows/.github/workflows/publish_node_package.yml@feat-npm-publish-outputs'
    with:
      package_name: flowforge-driver-localfs
      package_dependencies: |
        @flowforge/nr-launcher
  
  debug:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Print release name from package job
        run: echo ${{ needs.package.outputs.release_name }}


  dispatch:
    runs-on: ubuntu-latest
    needs: package
    if: false
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_BOT_APP_ID }}
          private_key: ${{ secrets.GH_BOT_APP_KEY }}

      - name: Trigger flowforge package rebuild
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish.yml
          repo: flowforge/flowforge
          ref: feat-publish-pipeline-poc
          token: ${{ steps.generate_token.outputs.token }}
          inputs: '{"localfs_ref": "${{ github.ref }}", "localfs_release_name": "${{ needs.package.outputs.release_name }}"}'