name: Publish
on:
  workflow_dispatch:
    inputs:
      nr_launcher_release_name:
        description: 'flowforge-nr-launcher package version'
        required: false
        default: 'nightly'
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - 'feat-*' 

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: debug payload
        run: echo ${{ github.event.client_payload.nr_launcher_release_name }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set nigthly release
        # if: ${{ github.event_name == 'schedule' }}
        run: echo "release_name=nightly" >> $GITHUB_ENV
      - name: "Set dependecies versions"
        run: |
          npm version prerelease --preid `git rev-parse --short HEAD`-`date +%Y%m%d` --no-git-tag-version
          cat package.json | jq '.dependencies["@flowforge/nr-launcher"] = "${{ env.release_name }}"' > package.json-patched
          mv package.json-patched package.json
      - name: "publish flowforge-driver-localfs"
        uses: JS-DevTools/npm-publish@v2
        with:
          tag: ${{ env.release_name }}
          package: ./package.json
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}